import * as React from "react";

const SpinnerIcon = (props: React.ComponentProps<"svg">) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    style={{
      margin: "auto",
      background: "0 0",
      display: "block",
      shapeRendering: "auto",
    }}
    width={200}
    height={200}
    viewBox="0 0 100 100"
    preserveAspectRatio="xMidYMid"
    {...props}
  >
    <rect x={46} y={5} rx={2.7} ry={2.7} width={8} height={18} fill="#94a3b8">
      <animate
        attributeName="opacity"
        values="1;0"
        keyTimes="0;1"
        dur="1s"
        begin="-0.9375s"
        repeatCount="indefinite"
      />
    </rect>
    <rect
      x={46}
      y={5}
      rx={2.7}
      ry={2.7}
      width={8}
      height={18}
      fill="#94a3b8"
      transform="rotate(22.5 50 50)"
    >
      <animate
        attributeName="opacity"
        values="1;0"
        keyTimes="0;1"
        dur="1s"
        begin="-0.875s"
        repeatCount="indefinite"
      />
    </rect>
    <rect
      x={46}
      y={5}
      rx={2.7}
      ry={2.7}
      width={8}
      height={18}
      fill="#94a3b8"
      transform="rotate(45 50 50)"
    >
      <animate
        attributeName="opacity"
        values="1;0"
        keyTimes="0;1"
        dur="1s"
        begin="-0.8125s"
        repeatCount="indefinite"
      />
    </rect>
    <rect
      x={46}
      y={5}
      rx={2.7}
      ry={2.7}
      width={8}
      height={18}
      fill="#94a3b8"
      transform="rotate(67.5 50 50)"
    >
      <animate
        attributeName="opacity"
        values="1;0"
        keyTimes="0;1"
        dur="1s"
        begin="-0.75s"
        repeatCount="indefinite"
      />
    </rect>
    <rect
      x={46}
      y={5}
      rx={2.7}
      ry={2.7}
      width={8}
      height={18}
      fill="#94a3b8"
      transform="rotate(90 50 50)"
    >
      <animate
        attributeName="opacity"
        values="1;0"
        keyTimes="0;1"
        dur="1s"
        begin="-0.6875s"
        repeatCount="indefinite"
      />
    </rect>
    <rect
      x={46}
      y={5}
      rx={2.7}
      ry={2.7}
      width={8}
      height={18}
      fill="#94a3b8"
      transform="rotate(112.5 50 50)"
    >
      <animate
        attributeName="opacity"
        values="1;0"
        keyTimes="0;1"
        dur="1s"
        begin="-0.625s"
        repeatCount="indefinite"
      />
    </rect>
    <rect
      x={46}
      y={5}
      rx={2.7}
      ry={2.7}
      width={8}
      height={18}
      fill="#94a3b8"
      transform="rotate(135 50 50)"
    >
      <animate
        attributeName="opacity"
        values="1;0"
        keyTimes="0;1"
        dur="1s"
        begin="-0.5625s"
        repeatCount="indefinite"
      />
    </rect>
    <rect
      x={46}
      y={5}
      rx={2.7}
      ry={2.7}
      width={8}
      height={18}
      fill="#94a3b8"
      transform="rotate(157.5 50 50)"
    >
      <animate
        attributeName="opacity"
        values="1;0"
        keyTimes="0;1"
        dur="1s"
        begin="-0.5s"
        repeatCount="indefinite"
      />
    </rect>
    <rect
      x={46}
      y={5}
      rx={2.7}
      ry={2.7}
      width={8}
      height={18}
      fill="#94a3b8"
      transform="rotate(180 50 50)"
    >
      <animate
        attributeName="opacity"
        values="1;0"
        keyTimes="0;1"
        dur="1s"
        begin="-0.4375s"
        repeatCount="indefinite"
      />
    </rect>
    <rect
      x={46}
      y={5}
      rx={2.7}
      ry={2.7}
      width={8}
      height={18}
      fill="#94a3b8"
      transform="rotate(202.5 50 50)"
    >
      <animate
        attributeName="opacity"
        values="1;0"
        keyTimes="0;1"
        dur="1s"
        begin="-0.375s"
        repeatCount="indefinite"
      />
    </rect>
    <rect
      x={46}
      y={5}
      rx={2.7}
      ry={2.7}
      width={8}
      height={18}
      fill="#94a3b8"
      transform="rotate(225 50 50)"
    >
      <animate
        attributeName="opacity"
        values="1;0"
        keyTimes="0;1"
        dur="1s"
        begin="-0.3125s"
        repeatCount="indefinite"
      />
    </rect>
    <rect
      x={46}
      y={5}
      rx={2.7}
      ry={2.7}
      width={8}
      height={18}
      fill="#94a3b8"
      transform="rotate(247.5 50 50)"
    >
      <animate
        attributeName="opacity"
        values="1;0"
        keyTimes="0;1"
        dur="1s"
        begin="-0.25s"
        repeatCount="indefinite"
      />
    </rect>
    <rect
      x={46}
      y={5}
      rx={2.7}
      ry={2.7}
      width={8}
      height={18}
      fill="#94a3b8"
      transform="rotate(270 50 50)"
    >
      <animate
        attributeName="opacity"
        values="1;0"
        keyTimes="0;1"
        dur="1s"
        begin="-0.1875s"
        repeatCount="indefinite"
      />
    </rect>
    <rect
      x={46}
      y={5}
      rx={2.7}
      ry={2.7}
      width={8}
      height={18}
      fill="#94a3b8"
      transform="rotate(292.5 50 50)"
    >
      <animate
        attributeName="opacity"
        values="1;0"
        keyTimes="0;1"
        dur="1s"
        begin="-0.125s"
        repeatCount="indefinite"
      />
    </rect>
    <rect
      x={46}
      y={5}
      rx={2.7}
      ry={2.7}
      width={8}
      height={18}
      fill="#94a3b8"
      transform="rotate(315 50 50)"
    >
      <animate
        attributeName="opacity"
        values="1;0"
        keyTimes="0;1"
        dur="1s"
        begin="-0.0625s"
        repeatCount="indefinite"
      />
    </rect>
    <rect
      x={46}
      y={5}
      rx={2.7}
      ry={2.7}
      width={8}
      height={18}
      fill="#94a3b8"
      transform="rotate(337.5 50 50)"
    >
      <animate
        attributeName="opacity"
        values="1;0"
        keyTimes="0;1"
        dur="1s"
        begin="0s"
        repeatCount="indefinite"
      />
    </rect>
  </svg>
);

export default SpinnerIcon;
